/* Every project, in one place.
   Add a demo later by dropping files in assets/media/<slug>/ and listing them in `media`.
   media entries: { type: 'video', src, poster } | { type: 'image', src } */

const DEVELOPER = "Chase McKenzie";

const PROJECTS = [
  {
    slug: "drop",
    title: "Drop",
    icon: "📲",
    accent: "#2fc4b2",
    accent2: "#0d4f47",
    tagline:
      "AirDrop for Windows — scan a QR code and your phone and PC share one live tray, over your own wifi.",
    genres: ["Web App", "Tool"],
    tags: ["Node.js", "LAN", "QR", "File Transfer", "SSE", "Zero Config"],
    released: "2026-08-15",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/drop",
    linkLabel: "View on GitHub",
    features: ["No app on the phone", "Nothing leaves your network", "Live on both sides", "Streams large files"],
    tech: {
      Runtime: "Node 22, one dependency",
      Transport: "PUT with a raw body — no multipart parser",
      Live: "Server-sent events push both directions",
      Pairing: "In-memory code encoded in a QR, cookie-scoped session",
      Media: "Range requests honoured so iOS plays video inline",
    },
    about: [
      "Getting a photo off my phone and onto my PC meant emailing it to myself. Drop replaces that: run it, point your phone's camera at the QR code on screen, and both devices are looking at the same tray. Anything either side adds appears on the other instantly.",
      "There is nothing to install on the phone — it is just a web page served off the PC. Files are never uploaded anywhere; they sit in a folder on the machine that served them, and the only dependency in the project draws the QR code and makes no network calls of its own.",
      "Uploads skip multipart entirely. The filename rides in a header and the file is the raw request body, which means no parsing dependency and the request streams straight to disk instead of being buffered in memory. Range requests are honoured too, because iOS Safari flatly refuses to play a video inline without them.",
      "The interesting problem wasn't the transfer, it was the last mile: Windows blocks inbound connections by default and is stricter still on a network marked Public, so the PC looks perfectly healthy while the phone spins forever. Drop checks for its own firewall rule at startup and tells you, rather than letting it read as a broken app.",
    ],
    highlights: [
      "Scan once — no app, no account, no cloud",
      "Drag onto the window, or Ctrl+V a screenshot straight across",
      "Both devices update live, no refresh",
      "Warns you about the firewall instead of just failing",
    ],
    cover: "assets/media/drop/cover.png",
    media: [
      { type: "image", src: "assets/media/drop/home.png" },
    ],
  },
  {
    slug: "rigbridge",
    title: "RigBridge",
    icon: "🦴",
    accent: "#f0a422",
    accent2: "#6b4409",
    tagline:
      "A bridge that lets an AI agent animate Roblox characters inside Blender — and hand the result straight to Roblox.",
    genres: ["Tool", "Desktop"],
    tags: ["Blender", "Python", "MCP", "Roblox", "Animation", "Open Cloud"],
    released: "2026-08-14",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/rigbridge",
    linkLabel: "View on GitHub",
    features: ["Real Blender keyframes", "Rendered previews", "Publishes to Roblox", "Hand-editable at any point"],
    tech: {
      Halves: "Blender add-on (local socket) + MCP server that forwards to it",
      Output: "Ordinary keyframes on ordinary bones — no proprietary format",
      Preview: "Rendered viewport images, so the agent can see its own work",
      Publishing: "Roblox Open Cloud, one step from Blender to an assetId",
      Rig: "R6 IK rigs with constraint-driven export bones",
    },
    about: [
      "Animating for Roblox means either the in-Studio animation editor or a manual Blender round-trip. This is a third option: a Blender add-on exposing the rig over a local socket, and an MCP server on the other end, so an agent can build a rig, pose it, key it, and look at rendered previews of what it just made.",
      "The design rule is that nothing is locked away. Everything lands as ordinary Blender keyframes on ordinary bones, so I can grab the timeline at any point, edit by hand, and have the changes read back — the agent is a collaborator on the file, not an opaque generator that owns it.",
      "Publishing is the part that usually breaks. RigBridge goes from a Blender action to a live Roblox assetId in one step through Open Cloud, with a dry-run mode and a written manifest, because every publish creates a new permanent asset and there is no undo.",
      "It has done real work: all eighteen of the animations my Roblox project was missing went up through it in a single pass, ids recorded, and the game's movement code was wired against them the same day.",
    ],
    highlights: [
      "Poses the control rig, bakes from the export rig",
      "Renders previews so the result can be checked, not assumed",
      "One step from Blender action to live Roblox assetId",
      "18 animations published through it in one pass",
    ],
    media: [],
  },
  {
    slug: "volt",
    title: "Volt",
    icon: "⚡",
    accent: "#8b6cf0",
    accent2: "#33206e",
    tagline:
      "A terminal that looks like yours — real ConPTY shells, Warp-style command blocks, and a side rail for parallel sessions.",
    genres: ["Desktop", "Tool"],
    tags: ["Electron", "ConPTY", "Terminal", "Win32", "WebView2", "Themes"],
    released: "2026-08-13",
    status: "In Development",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/volt",
    linkLabel: "View on GitHub",
    features: ["Every Windows shell", "Command blocks with exit codes", "Fuzzy palette over your history", "Eight themes"],
    tech: {
      Shells: "PowerShell, pwsh, cmd, Git Bash, WSL — real ConPTY, not emulation",
      Blocks: "Per-command gutter dot, scrollbar tick, exit code, duration",
      Palette: "Fuzzy search over everything you have ever run",
      Sessions: "Side rail so two agent sessions run at once",
      Rewrite: "In-progress C# Win32 + WebView2 host — 349 MB down to 0.9 MB",
    },
    about: [
      "Windows Terminal runs shells well and does nothing else. Volt keeps the shells — real ConPTY-backed PowerShell, pwsh, cmd, Git Bash and WSL — and adds the layer I actually wanted on top.",
      "Every command becomes a tracked block: a coloured dot in the gutter, a tick in the scrollbar, the exit code, and how long it took. Click the dot to re-run it, copy the command, or copy its entire output without selecting a single character.",
      "The side rail exists because I run more than one agent session at a time and kept losing track of which window was which. Sessions live in a rail with their own state and background notifications, so a finished job announces itself instead of waiting to be noticed.",
      "It is currently being taken off Electron. A hand-written C# Win32 + WebView2 host passes all six risk spikes and takes the shipped size from 349 MB to 0.9 MB; the bridge layer is not ported yet, which is why this is still marked in development rather than shipped.",
    ],
    highlights: [
      "Real ConPTY, every Windows shell",
      "Command blocks: exit code, duration, one-click re-run",
      "Side rail for parallel sessions with background notifications",
      "De-Electron spike: 349 MB → 0.9 MB",
    ],
    cover: "assets/media/volt/cover.png",
    media: [
      { type: "image", src: "assets/media/volt/home.png" },
    ],
  },
  {
    slug: "arkham-joker-mod",
    title: "Playable Joker",
    icon: "🃏",
    accent: "#6cbf3f",
    accent2: "#2d5016",
    tagline:
      "A Batman: Arkham Knight mod that makes the Joker playable — built on a hand-written Unreal Engine 3 mesh-merge tool.",
    genres: ["Game", "Mod"],
    tags: ["Unreal Engine 3", "Reverse Engineering", "Python", "Blender", "Modding", "Binary Formats"],
    released: "2026-08-12",
    status: "In Development",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/arkham-joker-mod",
    linkLabel: "View on GitHub",
    features: ["Real mesh swap, not a reskin", "Hand-authored umbrella glide", "Recoloured UI", "Validated against a known tool"],
    tech: {
      Target: "Unreal Engine 3, package version 863, licensee 0x8083",
      Tooling: "Hand-written .upk parser and mesh-merge in Python",
      Authoring: "Umbrella modelled, rigged and glide-animated in Blender",
      Scope: "All 19 damage-state packages rebuilt and installed",
      Validation: "Byte-diffed against UPK Explorer — 116 differing bytes, all name-order",
    },
    about: [
      "The premise: play Arkham Knight as the Joker, with his own weapons, the Jokerfied Batmobile, and an umbrella glide in place of the cape. The research pass found most of the assets already ship with the game — the Joker player package is 15 MB and 6,771 exports, not a stub — so the work is mostly rebinding rather than authoring.",
      "The first attempt swapped whole files by renaming, and it crashed the game: a package that should have held 1,187 exports came out with 9. It parsed cleanly and was still completely wrong, which is the lesson the rest of the project is built on — always diff the counts against the file you replaced.",
      "What replaced it is a real UE3 mesh-merge tool that imports the Joker *into* the full package, so materials, ragdoll data and animation trees survive the transplant. All nineteen damage-state packages are built and installed, and the output was byte-diffed against an established tool's: 116 differing bytes, every one of them name-ordering, nothing unexplained.",
      "The umbrella is the one part with no source asset — modelled, rigged and glide-animated from scratch — and 48 UI textures were recoloured green to match.",
    ],
    highlights: [
      "Hand-written UE3 package parser and mesh-merge tool",
      "Materials, ragdoll and anim trees survive the swap",
      "Output validated byte-for-byte against a known-good tool",
      "Umbrella modelled, rigged and animated from nothing",
    ],
    media: [],
  },
  {
    slug: "kickflip",
    title: "Kickflip",
    icon: "🛹",
    accent: "#ff4d6d",
    accent2: "#6b1226",
    tagline:
      "Point a phone at yourself, skate, and it names the trick, scores it, and tells you what to fix.",
    genres: ["Web App", "Mobile"],
    tags: ["Computer Vision", "Pose Tracking", "On-Device", "Camera", "Skateboarding", "TensorFlow.js"],
    released: "2026-08-09",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/kickflip",
    linkLabel: "View on GitHub",
    features: ["Runs entirely on-device", "217-trick catalogue", "Skate 3-style readout", "Analyses clips you already filmed"],
    tech: {
      Inference: "In-browser, on-device — no upload, no server doing the thinking",
      Trackers: "Two — one for the body, a separate one for the board",
      Transport: "Self-signed HTTPS, because getUserMedia refuses plain LAN http",
      Dataset: "YouTube harvest → segment → benchmark pipeline",
      Catalogue: "217 tricks",
    },
    about: [
      "Prop a phone side-on to where you're skating, hit start, and it reads what you did — with a Skate 3-style readout in the corner. Everything runs in the browser on the device; nothing is uploaded and no server does the thinking.",
      "The core insight is that pose alone cannot tell a kickflip from a heelflip. Your body is in almost exactly the same place either way — what differs is the board. So there are two trackers, and the board one is what actually names the trick.",
      "Getting the camera at all is its own fight: getUserMedia refuses to hand over a camera on a plain LAN http:// origin, so the server self-signs a certificate on first run and caches it, and the phone warns once before letting you in.",
      "Testing it against real footage rather than my own demo clips paid for itself immediately — it surfaced a deadlock that meant the detector could never fire at all, on any input. There is a full harvest → segment → benchmark pipeline against real YouTube clips so that class of bug gets caught by data instead of by luck.",
    ],
    highlights: [
      "Tracks the board separately — the only way to name a flip trick",
      "Fully on-device, no upload, no account",
      "Real-footage benchmark pipeline, not demo clips",
      "217-trick catalogue with coaching feedback",
    ],
    cover: "assets/media/kickflip/cover.png",
    media: [
      { type: "image", src: "assets/media/kickflip/home.png" },
    ],
  },
  {
    slug: "warmer",
    title: "Warmer",
    icon: "📡",
    accent: "#ff6b35",
    accent2: "#7a2a0e",
    tagline:
      "Find your things by walking around — a Geiger counter for Bluetooth, running on real radio signal.",
    genres: ["Web App", "Tool"],
    tags: ["Bluetooth", "WinRT", "C#", "Node.js", "SSE", "Hardware"],
    released: "2026-08-08",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/warmer",
    linkLabel: "View on GitHub",
    features: ["Real Bluetooth, not simulated", "Analog needle that clicks", "Identify a device by moving it", "Nothing leaves the machine"],
    tech: {
      Radio: "WinRT BLE scanner, built from source on first run",
      Transport: "Native scanner → Node → SSE → browser",
      Meter: "Analog needle, red→green bar, live distance in feet",
      Identification: "Fade-ranked motion test for devices that don't advertise a name",
      Dependencies: "None",
    },
    about: [
      "Add your Bluetooth devices, tap one, and you get a Geiger counter: a needle that clicks faster as you close in, a bar that runs red to green, and a live distance in feet. The list is not a mock — it is what your radio can actually hear at that moment.",
      "The real problem is that most radios don't say who they are. On a typical scan only about three devices in twenty advertise a name; the rest are 'Apple device' and a meaningless address. So there is a second way in: identify it by moving it.",
      "Rest the device on the PC for a six-second close-up reading, then carry it as far away as you can for eighteen. Everything else in the house stayed put — yours is the signal that collapsed, and candidates are ranked by how far each faded. A device that disappears entirely ranks highest, because walking out of range is the strongest evidence there is.",
      "Candidates that were never loud during the close-up are discarded, since a weak radio at the edge of range drifts in and out on its own and that looks exactly like a huge fade.",
    ],
    highlights: [
      "Real BLE hardware, no simulation anywhere",
      "Analog proximity meter with audible clicks",
      "Finds unnamed devices by how their signal fades",
      "Zero dependencies — the scanner builds itself",
    ],
    cover: "assets/media/warmer/cover.png",
    media: [
      { type: "image", src: "assets/media/warmer/home.png" },
    ],
  },
  {
    slug: "studio-hud",
    title: "Studio HUD",
    icon: "🎛",
    accent: "#d97757",
    accent2: "#5c2b17",
    tagline:
      "A Roblox Studio plugin that shows what your AI agent is doing right now — and sends your selection back to it.",
    genres: ["Tool", "Roblox"],
    tags: ["Roblox Studio", "Plugin", "Luau", "Node.js", "Dev Tool", "Hooks"],
    released: "2026-08-07",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/studio-hud",
    linkLabel: "View on GitHub",
    features: ["Live tool-call feed", "Selection bridge", "Activity sparkline", "Health pills for every service"],
    tech: {
      Shape: "Agent hooks → Node bridge → Studio plugin polling",
      Panel: "In-flight call with a millisecond timer, 60s sparkline, last 14 calls",
      Bridge: "Selection pushed back out as JSON the agent reads",
      Health: "Live pills for the bridge, Rojo, and the agent session",
      Detail: "Real class icons and full instance paths",
    },
    about: [
      "When an AI agent is editing your Roblox place through an MCP server, two things are missing: you can't see what it is doing, and it can't see what you are looking at. This plugin is both directions of that.",
      "The panel shows the in-flight tool call with a timer that ticks between polls, a sparkline of the last sixty seconds of activity, and the last fourteen calls with durations and ages. Categories are colour-coded — read, edit, find, run — and failed calls turn red, so a run going wrong is visible at a glance instead of buried in a transcript.",
      "The other half is the selection bridge. Click an instance in the Explorer and its real class icon, name and full path go straight to the agent, with a receipt in the panel confirming it landed. It removes the single most tedious part of the workflow: pasting instance paths by hand.",
      "It is a companion to the MCP server rather than a replacement — the MCP already does the reading and editing, this is purely the part that lets a human and an agent see each other.",
    ],
    highlights: [
      "Live tool-call feed with millisecond timing",
      "Explorer selection sent across with one click",
      "Health pills for bridge, Rojo and session",
      "Colour-coded categories, failures in red",
    ],
    media: [],
  },
  {
    slug: "mod-loader",
    title: "Mod Loader",
    icon: "🧩",
    accent: "#57c785",
    accent2: "#1d4a30",
    tagline:
      "One mod manager for every game on the PC — detects your library, then installs mods from whichever host each game actually uses.",
    genres: ["Desktop", "Tool"],
    tags: ["Electron", "Node.js", "Modding", "Minecraft", "Steam", "APIs"],
    released: "2026-08-06",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/modloader",
    linkLabel: "View on GitHub",
    features: ["Auto-detects installed games", "Dependency resolution", "Offline-first artwork", "Never deletes files"],
    tech: {
      Runtime: "Electron 33, Node 22",
      Security: "contextIsolation on, nodeIntegration off, all IPC named",
      Sources: "Modrinth v2, Thunderstore, CurseForge Core v1",
      Detection: "Steam libraryfolders.vdf, Epic manifests, XboxGames, .minecraft",
      Identification: "SHA-512 hash lookup, not filename matching",
    },
    about: [
      "I had three mod managers installed — CurseForge, Modrinth and Thunderstore — doing one job between them. This replaces all three. It scans Steam (every library folder), Epic, Xbox and Minecraft, finds 44 games on my machine, and sorts them by what can actually be done with each.",
      "Installed mods are identified by the SHA-512 of the jar rather than its filename, so Modrinth returns the exact project and version with no fuzzy matching. Anything it doesn't recognise still gets listed, read from the jar's own metadata, labelled honestly instead of hidden.",
      "It's provider-driven rather than pretending every game works the same. Minecraft and the BepInEx games get real search and one-click install with dependency resolution. Nexus games deliberately don't — Nexus refuses download links to third-party apps on free accounts, so that path explains why and hands off to the browser instead of failing at the last step.",
      "Because it writes into game folders, it's careful: nothing is ever hard-deleted, downloads are verified against the published checksum before being renamed into place, and zip extraction is guarded against path traversal.",
    ],
    highlights: [
      "Finds 44 games across Steam, Epic, Xbox and Minecraft",
      "Identifies mods by file hash, not by filename",
      "Installs dependencies recursively in one click",
      "Honest about what each mod host actually allows",
    ],
    cover: "assets/media/mod-loader/cover.png",
    media: [
      { type: "image", src: "assets/media/mod-loader/home.png" },
      { type: "image", src: "assets/media/mod-loader/minecraft.png" },
      { type: "image", src: "assets/media/mod-loader/thunderstore.png" },
      { type: "image", src: "assets/media/mod-loader/nexus.png" },
    ],
  },
  {
    slug: "shinobi-legends",
    title: "Shinobi Legends",
    icon: "🍥",
    accent: "#e8622c",
    accent2: "#7c2d12",
    tagline:
      "A Naruto-themed Roblox action RPG — chakra natures, combo combat, quests, and a hand-built Konoha.",
    genres: ["Game", "Roblox"],
    tags: ["Action RPG", "Multiplayer", "Luau", "Combat", "Open World", "Rojo"],
    released: "2026-08-01",
    status: "In Development",
    priceLabel: "Free to Play",
    link: "https://payhip.com/CoolRobloxAssets",
    linkLabel: "Get the assets",
    features: ["Multiplayer", "Controller support", "Server-authoritative", "Saves progress"],
    tech: {
      Language: "Luau",
      Engine: "Roblox Studio",
      Sync: "Rojo (filesystem → place file)",
      Architecture: "Server-authoritative combat, client prediction",
      Assets: "Real R6 character rigs, hand-built village geometry",
    },
    about: [
      "A Blox Fruits-style action RPG built on Roblox. You spawn into a hand-built Konoha, pick up quests from villagers, and fight your way outward through progressively nastier enemy camps.",
      "Combat is a real combo system rather than a click-damage loop: light attacks chain, chakra natures modify what those chains do, and enemies have their own AI states — patrol, aggro, reposition, retreat — so fights move around rather than standing still.",
      "The village isn't procedural filler. It's built geometry baked into the place file, with the quest-givers, shops, and training areas placed where they make sense to walk between.",
    ],
    highlights: [
      "Combo-chain melee with chakra nature modifiers",
      "Enemy AI with patrol, aggro and retreat states",
      "Quest system wired to NPCs in a hand-built Konoha",
      "Real R6 rigs, not placeholder blocks",
    ],
    media: [],
  },
  {
    slug: "creator-hub-plus",
    title: "Creator Hub Plus",
    icon: "📊",
    accent: "#3aa0ff",
    accent2: "#0f3d66",
    tagline:
      "A Chrome extension that turns the Roblox Creator Hub into a real dashboard — stats, notes, and a kanban board per game.",
    genres: ["Extension", "Roblox"],
    tags: ["Chrome Extension", "MV3", "Analytics", "Kanban", "Roblox", "Dashboard"],
    released: "2026-08-01",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/creator-hub",
    linkLabel: "View on GitHub",
    features: ["Syncs across devices", "Read-only — never writes to Roblox", "Works offline", "Local history"],
    tech: {
      Platform: "Chrome / Edge, Manifest V3",
      Language: "Vanilla JS, no framework",
      Storage: "chrome.storage.sync + local",
      Network: "Read-only GETs against Roblox public APIs",
      Mount: "Inline panel on create.roblox.com + toolbar popup",
    },
    about: [
      "The Roblox Creator Hub tells you almost nothing about your own games over time. Creator Hub Plus lists your experiences newest-first, lets you star the ones you care about, and opens any of them into three tabs: Stats, Notes, and Board.",
      "Stats shows total visits with a 7-day delta, live players, favourites, like ratio, and a growth sparkline. Roblox exposes no historical data at all, so the extension records its own daily snapshots from the day you install it — the chart fills in over time.",
      "Notes is a per-game scratchpad that autosaves. Board is a per-game kanban (To do / In progress / Done) with drag-and-drop, and the open-card count shows as a badge on the game's row so you can see at a glance which project has work parked against it.",
      "It mounts inline on the Creator Hub dashboard itself, which means finding an anchor inside a React app that reshuffles its DOM without warning — handled with a resilient anchor strategy so it doesn't break when Roblox ships a redesign.",
    ],
    highlights: [
      "Records its own daily history — Roblox exposes none",
      "Per-game kanban board with drag-and-drop",
      "Favourites sync across every signed-in Chrome",
      "Toolbar badge shows total concurrent players",
    ],
    cover: "assets/media/creator-hub-plus/cover.png",
    media: [
      { type: "image", src: "assets/media/creator-hub-plus/home.png" },
    ],
  },
  {
    slug: "amplify",
    title: "Amplify",
    icon: "🎨",
    accent: "#fc3c44",
    accent2: "#5b1220",
    tagline: "Spicetify, but for the Apple Music web player. Eight themes, animated backgrounds, and a custom CSS box.",
    genres: ["Extension", "Tool"],
    tags: ["Chrome Extension", "Theming", "Apple Music", "CSS", "Customization", "Live Preview"],
    released: "2026-07-31",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/amplify",
    linkLabel: "View on GitHub",
    features: ["Applies live, no reload", "Custom CSS supported", "Eight built-in themes", "Your own background image"],
    tech: {
      Platform: "Chrome / Edge, Manifest V3",
      Language: "Vanilla JS + CSS custom properties",
      Approach: "Overrides Apple's own CSS tokens and data-testid hooks",
      "Why not classes": "Apple's Svelte class names are hashed and change every deploy",
    },
    about: [
      "music.apple.com looks the same for everyone and Apple gives you no say in it. Amplify is a Chrome extension that restyles the whole player: eight theme presets, a custom accent colour, animated aurora backgrounds or your own photo, glass chrome, artwork glow, corner radius, sidebar width, UI scale, density, and font family.",
      "Everything applies live — change a setting and the page updates under you, no reload.",
      "The interesting constraint is that Apple Music is a Svelte app with hashed class names that change on every deploy, so styling against them would break within a week. Amplify instead themes through Apple's own CSS custom properties and stable `data-testid` attributes, which survive redeploys.",
      "There's also a raw custom-CSS box for anything the presets don't cover.",
    ],
    highlights: [
      "Eight presets: Midnight, Aurora, Sunset, Vapor, Forest, Nord, Mono, Daylight",
      "Animated backgrounds, or upload your own with blur + dim",
      "Layout controls: radius, sidebar width, scale, density, font",
      "Themes via stable CSS tokens, not brittle hashed classes",
    ],
    cover: "assets/media/amplify/cover.png",
    media: [
      { type: "image", src: "assets/media/amplify/home.png" },
    ],
  },
  {
    slug: "youtube-stats",
    title: "YouTube Stats",
    icon: "⏳",
    accent: "#ff0033",
    accent2: "#4a0512",
    tagline:
      "Tracks what you actually watch on YouTube — time, categories, top creators — in a panel built to look like it shipped with the site.",
    genres: ["Extension", "Tool"],
    tags: ["Chrome Extension", "MV3", "Analytics", "Privacy", "YouTube", "Data Export"],
    released: "2026-07-31",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/youtube-stats",
    linkLabel: "View on GitHub",
    features: ["Zero network permissions", "All data stays local", "JSON export", "Native-looking UI"],
    tech: {
      Platform: "Chrome / Edge, Manifest V3",
      Permissions: "None for network — the extension literally cannot phone home",
      Storage: "chrome.storage.local",
      "Hard part": "Reading player-response from the page's MAIN world across the isolated-world boundary",
    },
    about: [
      "A Chrome extension that tracks your real YouTube usage: videos watched, total time, a breakdown by category, a leaderboard of your top five creators, and a last-7-days chart. A red hourglass pill appears in the YouTube masthead, left of Create — it's styled to look like it shipped with the site.",
      "The measurements are deliberately honest. A video only counts once you've spent 30 seconds on it (or half its length, if shorter), so mis-clicks and flicked-past Shorts don't inflate the number. Watch time counts wall-clock seconds during which playback actually advanced, so seeking, buffering, ads and 2x speed all behave sensibly instead of quietly lying to you.",
      "Category data only exists inside YouTube's player-response object, which content scripts can't see. A MAIN-world bridge script reads it and posts it across the isolated-world boundary, catching it three separate ways — initial HTML, soft-navigation events, and a fetch hook on /youtubei/v1/player — so no navigation path is missed.",
      "The extension requests no network permissions at all. Nothing it records can leave your browser.",
    ],
    highlights: [
      "Watch time that survives seeking, buffering, ads and 2x speed",
      "Categories read from YouTube's own player response",
      "Top-creator leaderboard and 7-day history",
      "No network permissions — data physically cannot leave",
    ],
    cover: "assets/media/youtube-stats/cover.png",
    media: [
      { type: "image", src: "assets/media/youtube-stats/home.png" },
    ],
  },
  {
    slug: "wayback-time-machine",
    title: "Wayback Time Machine",
    icon: "🕰️",
    accent: "#8b6ef0",
    accent2: "#2b1d5c",
    tagline: "Browse any website as it looked in the past — a time-travel front end for the Internet Archive.",
    genres: ["Extension", "Tool"],
    tags: ["Chrome Extension", "Internet Archive", "History", "Web", "Time Travel"],
    released: "2026-07-30",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/wayback-time-machine/",
    linkLabel: "Open Preview",
    repo: "https://github.com/chaseMckenzie88/wayback-time-machine",
    features: ["One-click time travel", "Works on any site", "No account needed"],
    tech: {
      Platform: "Chrome / Edge extension",
      API: "Internet Archive Wayback availability API",
      Note: "The hosted preview is partial — extension APIs don't exist on a plain web page",
    },
    about: [
      "Pick a year, keep browsing. Wayback Time Machine takes whatever site you're on and swaps you into the Internet Archive's snapshot of it from the date you choose, so you can wander an old version of the web the way you'd wander the current one.",
      "It resolves the nearest available capture through the Archive's availability API rather than guessing at snapshot URLs, so you land on a page that actually exists instead of a 404.",
      "The GitHub Pages link is a partial preview — the real thing is a browser extension, and extension APIs don't exist on a plain hosted page.",
    ],
    highlights: [
      "Time-travel any URL you're already on",
      "Resolves the nearest real capture, not a guessed URL",
      "No account, no key, no setup",
    ],
    cover: "assets/media/wayback-time-machine/cover.png",
    media: [
      { type: "image", src: "assets/media/wayback-time-machine/home.png" },
    ],
  },
  {
    slug: "roblox-tracker",
    title: "Roblox Playtime Tracker",
    icon: "⏱️",
    accent: "#00a2ff",
    accent2: "#08304d",
    tagline:
      "Tracks how long you spend in each Roblox game and surfaces your most-played titles right on the Roblox home page.",
    genres: ["Extension", "Roblox"],
    tags: ["Chrome Extension", "Roblox", "Tracking", "Pinning", "Import/Export"],
    released: "2026-07-30",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/roblox-tracker/",
    linkLabel: "Open Preview",
    repo: "https://github.com/chaseMckenzie88/roblox-tracker",
    features: ["Pin favourites", "JSON export / import", "Prevent AFK kick", "Popup dashboard"],
    tech: {
      Platform: "Chrome / Edge, Manifest V3",
      Tracking: "Service worker, focus-aware page timing",
      Injection: "Content script adds a Most Played row to the Roblox home page",
      Limitation: "Browser only — the standalone Roblox app is invisible to any extension",
    },
    about: [
      "Roblox will not tell you how many hours you've sunk into anything. This extension counts it for you: while you're on a game page with the window focused, it banks the time against that game, then adds a Most Played row to the Roblox home page above Friends.",
      "Hover a card to pin a favourite. Flip the sort toggle to keep pinned games at the front. Export your whole history to JSON and restore it after a reinstall or on another machine.",
      "There's also a Prevent AFK kick toggle that keeps the roblox.com tab lightly active so it won't sign you out during long idle stretches.",
      "Two honest limitations, stated up front in the extension itself: it can only see games played through roblox.com in Chrome, and it starts from the day you install it — Roblox exposes no historical playtime to import.",
    ],
    highlights: [
      "Most Played row injected into the real Roblox home page",
      "Pin games and sort pinned-first",
      "Full JSON export/import for reinstalls",
      "Ships with its limitations written on the tin",
    ],
    cover: "assets/media/roblox-tracker/cover.png",
    media: [
      { type: "image", src: "assets/media/roblox-tracker/home.png" },
    ],
  },
  {
    slug: "custom-browser-tab",
    title: "Custom Browser Tab",
    icon: "🪟",
    accent: "#4fd1a5",
    accent2: "#0e4437",
    tagline:
      "A fully custom new-tab page: colour schemes, your own background, quick-start shortcuts, and drag-and-drop widgets.",
    genres: ["Extension", "Tool"],
    tags: ["Chrome Extension", "New Tab", "Widgets", "Weather", "Steam", "Customization"],
    released: "2026-07-30",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/custom-browser-tab/",
    linkLabel: "Open Preview",
    repo: "https://github.com/chaseMckenzie88/custom-browser-tab",
    features: ["First-run setup wizard", "Drag-and-drop widgets", "Custom background upload", "Chrome + Edge"],
    tech: {
      Platform: "Chrome / Edge, Manifest V3 (new-tab override)",
      Widgets: "Weather (no API key), Steam recently-played, quick-chat launcher",
      Search: "Uses your browser's real default search engine, falls back to Google",
      Storage: "Local config schema with defaults, images auto-resized before storing",
    },
    about: [
      "Replaces the new-tab page with something you actually choose. First run walks you through a name, a colour scheme with a custom accent, and which widgets you want.",
      "The search bar behaves like a normal new tab — type, hit enter, and it goes through your browser's configured default engine rather than hardcoding Google.",
      "Widgets are cards you can drag to reorder: current-temperature weather (one location permission, no API key), your Steam recently-played list, quick-start shortcut tiles with auto-fetched icons, and a one-click launcher for Claude, ChatGPT, or any URL.",
      "Backgrounds can be a preset scheme or your own photo, auto-resized before it's stored so the extension doesn't blow past the storage quota.",
      "Cash App balance was requested and deliberately left out — there's no public API for a personal balance, and the only way to get it would be scraping a logged-in session.",
    ],
    highlights: [
      "Drag-and-drop widget layout that persists",
      "Weather with no API key required",
      "Steam recently-played via your own free Web API key",
      "Upload any background — auto-resized before storage",
    ],
    cover: "assets/media/custom-browser-tab/cover.png",
    media: [
      { type: "image", src: "assets/media/custom-browser-tab/home.png" },
    ],
  },
  {
    slug: "vaultcheck",
    title: "VaultCheck",
    icon: "🔐",
    accent: "#f5b301",
    accent2: "#4d3800",
    tagline:
      "See your items, account level, and what it's worth across Roblox, Fortnite, Apex and Call of Duty. No passwords, ever.",
    genres: ["Web App", "Tool"],
    tags: ["Node.js", "Gaming", "Valuation", "Security", "Roblox", "Fortnite"],
    released: "2026-07-28",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/vaultcheck",
    linkLabel: "View on GitHub",
    features: ["No password field — by design", "Runs on your machine", "Real market valuations", "Four games"],
    tech: {
      Runtime: "Node.js — npm install && npm start",
      "Roblox data": "Public inventory API + Rolimons valuations",
      "Fortnite data": "Epic's own sign-in flow",
      "Security stance": "No password field exists anywhere in the app",
    },
    about: [
      "Type a Roblox username and get the full limiteds inventory with real valuations pulled from Rolimons, plus friends, followers, and account age. No login, no API key.",
      "It shows two numbers because both matter and they disagree. Value is what traders actually pay — community-maintained and resistant to manipulation. RAP is recent average price, which is trivially inflated by trading an item back and forth at a fake price. Items flagged Projected are called out individually, and the total warns you when any are present.",
      "USD conversion uses Roblox's official DevEx rate, and the app says plainly that this answers \"what would Roblox pay me for this\", not \"what would a trader pay\".",
      "The defining design decision is what isn't there: no password field, anywhere, ever. Every game covered either exposes the data publicly or provides its own sign-in page. Typing your game password into a third-party site is how accounts get stolen, and both Roblox and Epic ban for it.",
    ],
    highlights: [
      "Roblox limiteds with real Rolimons valuations",
      "Flags projected items instead of quietly inflating your total",
      "Fortnite locker through Epic's own sign-in",
      "Zero password handling by design",
    ],
    cover: "assets/media/vaultcheck/cover.png",
    media: [
      { type: "image", src: "assets/media/vaultcheck/home.png" },
    ],
  },
  {
    slug: "voice-notes",
    title: "Voice Notes",
    icon: "🎙️",
    accent: "#ffcc33",
    accent2: "#4a3800",
    tagline: "Apple Notes, laid out properly, with live speech-to-text that keeps up with you.",
    genres: ["Web App", "Tool"],
    tags: ["Single File", "Speech-to-Text", "Notes", "No Build Step", "Dark Mode", "Tabs"],
    released: "2026-07-27",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/voicenotes/",
    linkLabel: "Launch App",
    repo: "https://github.com/chaseMckenzie88/voicenotes",
    features: ["Runs from one HTML file", "Live dictation", "Keyboard shortcuts", "Follows system theme"],
    tech: {
      Stack: "One HTML file. No build step, no dependencies, no framework.",
      Speech: "Web Speech API, continuous mode with auto-restart",
      Layout: "Three panes — folders → note list → editor",
      Theme: "Follows your system light/dark preference",
    },
    about: [
      "A note-taking app laid out like the Apple Notes desktop app: three panes — folders with counts, a note list, and the editor — with a collapsible sidebar. The first line of a note is its title and names it everywhere.",
      "Dictation is the point. Words land in the note as you speak; the in-progress phrase shows in grey with a dotted underline, then converts to normal text once the engine finalises it. Listening is continuous and restarts itself through pauses instead of cutting out mid-thought.",
      "Spoken punctuation works — \"period\", \"comma\", \"question mark\", \"new paragraph\", and the rest — with auto-spacing and sentence capitalisation on top.",
      "Notes open in tabs. The yellow + opens a new one with the caret already on the title line, double-click a tab to rename it, Ctrl+Shift+D starts and stops dictation.",
      "The whole thing is a single HTML file with no dependencies. Open it and it works.",
    ],
    highlights: [
      "Continuous dictation that survives pauses",
      "Interim text shown in grey, then finalised in place",
      "Spoken punctuation and auto-capitalisation",
      "Tabbed notes with rename-in-place",
    ],
    cover: "assets/media/voice-notes/cover.png",
    media: [
      { type: "image", src: "assets/media/voice-notes/home.png" },
    ],
  },
  {
    slug: "yoink",
    title: "yoink",
    icon: "⬇️",
    accent: "#ff5c8a",
    accent2: "#4d0f22",
    tagline: "Local YouTube and Instagram → MP3/MP4 converter. Nothing is uploaded anywhere.",
    genres: ["Tool", "Web App"],
    tags: ["Python", "yt-dlp", "ffmpeg", "Local First", "Downloader", "Self-Hosted"],
    released: "2026-07-26",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://github.com/chaseMckenzie88/yoink",
    linkLabel: "View on GitHub",
    features: ["Entirely local", "Live progress + ETA", "Up to 4K", "No admin rights needed"],
    tech: {
      Backend: "Python + yt-dlp behind a small local web UI",
      ffmpeg: "Pulled in via imageio-ffmpeg and copied to bin/ automatically — no system install",
      Formats: "MP4 up to 4K, MP3 down to 96 kbps",
      Auth: "Optional Chrome cookie import for private / age-gated media",
    },
    about: [
      "Paste a link and a preview loads automatically — title, channel, duration, thumbnail. Pick MP4 (best / 4K / 1440p / 1080p / 720p / 480p / 360p) or MP3 (320 down to 96 kbps), hit Download, and watch progress, speed and ETA update live.",
      "Save sends the finished file to your browser downloads; Folder reveals it in Explorer. Either way it also lands in downloads/ on disk.",
      "Everything runs on your machine. Nothing is uploaded anywhere, and there's no server to trust.",
      "Setup is a virtualenv and a requirements install. ffmpeg comes in through imageio-ffmpeg and copies itself into bin/ on first run — no system install, no admin rights.",
      "For Instagram posts and age-gated YouTube, tick \"use Chrome cookies\" and yt-dlp reads your logged-in session.",
    ],
    highlights: [
      "Live progress, speed and ETA per job",
      "4K video or 320 kbps audio",
      "ffmpeg self-installs — no admin rights",
      "Chrome cookie import for private media",
    ],
    cover: "assets/media/yoink/cover.png",
    media: [
      { type: "image", src: "assets/media/yoink/home.png" },
    ],
  },
  {
    slug: "omnipost",
    title: "Omnipost",
    icon: "📆",
    accent: "#7c5cff",
    accent2: "#241a5c",
    tagline:
      "Record once, caption once, post everywhere on schedule. A Metricool-style dashboard for multi-platform video.",
    genres: ["Mobile", "SaaS"],
    tags: ["Kotlin", "Android", "Firebase", "Cloud Tasks", "Scheduling", "Video"],
    released: "2026-07-25",
    status: "In Development",
    priceLabel: "Unreleased",
    link: "https://github.com/chaseMckenzie88/omnipost",
    linkLabel: "View on GitHub",
    features: ["Scheduled publishing", "Per-platform analytics", "Cancel anything pending", "Survives app close"],
    tech: {
      Android: "Kotlin — dashboard, queue and new-post flow",
      Backend: "Firebase — Firestore, Cloud Storage, Cloud Functions",
      Scheduling: "Cloud Tasks with scheduleTime — nothing runs on the device",
      iOS: "Swift — not started, blocked on Mac access",
    },
    about: [
      "Record or import a video, edit it, write one caption, pick your platforms, choose a time — and Omnipost posts it everywhere on schedule. The dashboard is Metricool-shaped: per-platform analytics, a queue of what's going out and when, and a cancel button on anything still pending.",
      "Scheduling has to survive the app being closed and the phone being off, so none of it runs on the device. The app uploads the video to Cloud Storage, calls schedulePost, which validates and writes to Firestore and creates a Cloud Task with scheduleTime set to the requested moment. At that moment Cloud Tasks POSTs to publishWorker, which publishes to every selected platform and records each outcome independently.",
      "Per-target status is what makes partial failure survivable: if YouTube succeeds and TikTok 503s, the post is partially_failed, and the retry skips YouTube rather than double-posting to it.",
      "Status, honestly: the backend is written and typechecks but has never been run against a real platform API. The Android app is written but never compiled. OAuth connect flows aren't started, and nothing can publish until they are. Treat the first live run of each publish path as the real test.",
    ],
    highlights: [
      "Off-device scheduling via Cloud Tasks — survives phone off",
      "Per-platform publish outcomes recorded independently",
      "Retries skip platforms that already succeeded",
      "Cancel anything still in the queue",
    ],
    media: [],
  },
  {
    slug: "kiosk",
    title: "Kiosk",
    icon: "🛍️",
    accent: "#ff7a45",
    accent2: "#4d1d0c",
    tagline: "Your whole business, one link away. A creator storefront for digital products, courses, and coaching.",
    genres: ["Web App", "SaaS"],
    tags: ["Creator Economy", "Storefront", "Landing Page", "Auth", "Dashboard", "Pricing"],
    released: "2026-07-23",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/kiosk/",
    linkLabel: "Visit Site",
    repo: "https://github.com/chaseMckenzie88/kiosk",
    features: ["Marketing site + app", "Signup / login flow", "Seller dashboard", "Public storefront"],
    tech: {
      Stack: "Static HTML, CSS and JS — no framework",
      Pages: "Marketing, signup, login, dashboard, public store",
      Model: "Stan Store-style creator storefront",
    },
    about: [
      "A Stan Store clone: the simplest way for a creator to sell digital products, courses, and coaching calls from a single link.",
      "It's a complete product surface, not just a landing page — marketing site with features, three-step onboarding copy and pricing tiers, then signup and login, a seller dashboard for managing what you're selling, and the public-facing storefront a buyer actually lands on.",
      "The pitch it's built around: stop scattering your business across five links.",
    ],
    highlights: [
      "Full flow — marketing → signup → dashboard → live store",
      "Pricing tiers and three-step onboarding",
      "Public storefront page per creator",
    ],
    cover: "assets/media/kiosk/cover.png",
    media: [
      { type: "image", src: "assets/media/kiosk/home.png" },
    ],
  },
  {
    slug: "blitz",
    title: "Blitz",
    icon: "⚡",
    accent: "#ffd21e",
    accent2: "#4d3f00",
    tagline:
      "Describe what you built. Blitz finds the businesses that need it, their public emails, and drafts the outreach.",
    genres: ["SaaS", "Web App"],
    tags: ["Next.js", "Supabase", "Stripe", "AI", "Lead Generation", "B2B", "TypeScript"],
    released: "2026-07-23",
    status: "In Development",
    priceLabel: "$0 – $79/mo",
    link: "https://github.com/chaseMckenzie88/Blitz",
    linkLabel: "View on GitHub",
    features: ["Subscription billing", "CSV export", "Saved searches", "Drafted outreach"],
    tech: {
      Framework: "Next.js (App Router, TypeScript)",
      Database: "Supabase — auth + Postgres",
      Payments: "Stripe — checkout, customer portal, webhooks",
      AI: "Claude — query expansion, enrichment, message drafting",
      UI: "shadcn/ui + Tailwind",
    },
    about: [
      "Blitz turns a one-line description of your app into real leads. Tell it what you built and who it's for; it expands that into search queries, finds real businesses that fit, and looks up their public contact emails. You get a LinkedIn search link and a drafted message for every lead — you copy, tweak, and send it yourself.",
      "Built for solo devs shipping B2B tools, who have a product and no idea who to email about it.",
      "It's a full SaaS skeleton rather than a demo: Supabase auth and Postgres, Stripe checkout with a customer portal and webhook handling, saved searches you can revisit, per-lead detail pages, and CSV export. Three tiers — Free at 3 searches a month, Starter at $29 for 25, Pro at $79 for 100.",
    ],
    highlights: [
      "One sentence in, qualified leads out",
      "Public emails plus a LinkedIn search link per lead",
      "AI-drafted outreach you edit before sending",
      "Stripe subscriptions with real webhook handling",
    ],
    cover: "assets/media/blitz/cover.png",
    media: [
      { type: "image", src: "assets/media/blitz/home.png" },
    ],
  },
  {
    slug: "email-trace",
    title: "EmailTrace",
    icon: "🔎",
    accent: "#3ddc97",
    accent2: "#0d4433",
    tagline: "Find where your email is used — breaches, public profiles, and reputation across the web.",
    genres: ["Web App", "Tool"],
    tags: ["Single File", "OSINT", "Security", "Privacy", "HIBP", "Breach Check"],
    released: "2026-07-17",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/email-trace/",
    linkLabel: "Launch App",
    repo: "https://github.com/chaseMckenzie88/email-trace",
    features: ["Runs from one HTML file", "Keys stay in your browser", "Works without a key", "No backend"],
    tech: {
      Stack: "Single HTML file, no build, no backend",
      Sources: "Have I Been Pwned, EmailRep, public profile checks",
      Keys: "Stored in your browser, sent only to the API they belong to",
    },
    about: [
      "Type an email address and find out where it turns up: known data breaches, public profiles tied to it, and its overall reputation score.",
      "Basic checks work with no setup at all. Adding your own free API keys — Have I Been Pwned, EmailRep — unlocks the deeper breach and reputation data, and the app links you straight to where to get each one.",
      "There is no backend. Keys are saved in your browser and sent only to the API they belong to, never to any server of mine, because there isn't one. The whole app is a single HTML file.",
    ],
    highlights: [
      "Breach history via Have I Been Pwned",
      "Reputation scoring via EmailRep",
      "Works with zero setup, better with free keys",
      "No backend exists — nothing to leak",
    ],
    cover: "assets/media/email-trace/cover.png",
    media: [
      { type: "image", src: "assets/media/email-trace/home.png" },
    ],
  },
  {
    slug: "skill-learner",
    title: "Skill Learner",
    icon: "🎯",
    accent: "#5ac8fa",
    accent2: "#0d3a52",
    tagline: "Tell it what you're into. It hands you a skill worth learning and a tutorial to start with.",
    genres: ["Web App", "Tool"],
    tags: ["Single File", "Discovery", "Learning", "Reroll", "No Build Step"],
    released: "2026-07-15",
    status: "Shipped",
    priceLabel: "Free",
    link: "https://chasemckenzie88.github.io/skill-learner/",
    linkLabel: "Launch App",
    repo: "https://github.com/chaseMckenzie88/skill-learner",
    features: ["Instant results", "Difficulty rating", "Reroll in the same vein", "One tap to a tutorial"],
    tech: {
      Stack: "Single HTML file, no build, no dependencies",
      Flow: "Pick an interest → get a skill → watch a tutorial, reroll, or start over",
    },
    about: [
      "\"What are you into?\" — answer that, and Skill Learner gives you a concrete skill worth learning in that direction, with a difficulty tag attached.",
      "From there you can watch a tutorial for it in one tap, reroll for another skill in the same vein, or back out and pick a different interest entirely.",
      "It's built for the specific moment where you want to learn something but the blank page of \"learn what?\" stops you before you start.",
    ],
    highlights: [
      "Interest in, specific skill out",
      "Difficulty tagged on every suggestion",
      "Reroll within the same interest",
      "One tap straight to a tutorial",
    ],
    cover: "assets/media/skill-learner/cover.png",
    media: [
      { type: "image", src: "assets/media/skill-learner/home.png" },
    ],
  },
  {
    slug: "gutter-run",
    title: "Gutter Run",
    icon: "🛹",
    accent: "#a3e635",
    accent2: "#2c4008",
    tagline: "Endless skate. Jump cones, grind rails, drop the stair gap — touch the steps and you're done.",
    genres: ["Game", "Web App"],
    tags: ["Endless Runner", "Skateboarding", "Canvas", "Arcade", "High Score", "Single File"],
    released: "2026-07-14",
    status: "Shipped",
    priceLabel: "Free to Play",
    link: "https://chasemckenzie88.github.io/gutter-run/",
    linkLabel: "Play Now",
    repo: "https://github.com/chaseMckenzie88/gutter-run",
    features: ["Single-player", "Local high score", "Keyboard + touch", "Instant restart"],
    tech: {
      Stack: "Single HTML file, canvas rendering, no engine",
      Controls: "Space or tap to jump, tap again mid-air to stomp",
      Persistence: "Best score saved locally",
    },
    about: [
      "An endless skate sidescroller. Jump cones and potholes, land on a rail to grind it, drop into the stair gap and ollie out before the climb back up — touch those steps and the run is over.",
      "Tap jump again mid-air to stomp down fast, which is how you make tight gaps you'd otherwise sail past. Every trick you land pops up on screen as you pull it off.",
      "Space or tap to start. Your best score sticks around between sessions, and there's a reset if you want a clean slate.",
    ],
    highlights: [
      "Grind rails, clear gaps, stomp to land fast",
      "Trick names pop on screen as you land them",
      "One mistake on the stairs ends the run",
      "Keyboard and touch, no install",
    ],
    cover: "assets/media/gutter-run/cover.png",
    media: [
      { type: "image", src: "assets/media/gutter-run/home.png" },
    ],
  },
  {
    slug: "reflex-lab",
    title: "Reflex Lab",
    icon: "⚡",
    accent: "#f472b6",
    accent2: "#4a0f31",
    tagline: "How fast are you, actually? A reaction-time test that keeps your history.",
    genres: ["Game", "Tool"],
    tags: ["Reaction Time", "Benchmark", "History", "Single File", "Minimal"],
    released: "2026-07-13",
    status: "Shipped",
    priceLabel: "Free to Play",
    link: "https://chasemckenzie88.github.io/reflex-lab/",
    linkLabel: "Play Now",
    repo: "https://github.com/chaseMckenzie88/reflex-lab",
    features: ["Single-player", "Persistent history", "Resettable", "Works on mobile"],
    tech: {
      Stack: "Single HTML file, no dependencies",
      Timing: "High-resolution timers, randomised delays to defeat anticipation",
      Persistence: "Attempt history saved locally",
    },
    about: [
      "A clean reaction-time test. Wait for the signal, click as fast as you can, and it records the result — with randomised delays so you can't game it by anticipating the cue.",
      "Every attempt is kept, so you can see whether you're actually improving or just remembering your one good run. Reset history when you want to start fresh.",
      "One HTML file, no dependencies, works on a phone.",
    ],
    highlights: [
      "Randomised delays defeat anticipation",
      "Full attempt history, not just your best",
      "Resettable at any time",
    ],
    cover: "assets/media/reflex-lab/cover.png",
    media: [
      { type: "image", src: "assets/media/reflex-lab/home.png" },
    ],
  },
];

const GENRES = ["All", "Web App", "Extension", "Desktop", "Game", "SaaS", "Tool", "Mobile", "Roblox", "Mod"];
